name: TEST
on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
jobs:
  statbotics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: statbotics
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - run: npm i @openapitools/openapi-generator-cli -g
      - run: openapi-generator-cli generate -g rust -i https://api.statbotics.io/openapi.json -o .
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Generated Rust client library"
          git push origin HEAD:statbotics
  tba-read:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            ref: tba
        - uses: actions/setup-node@v4
          with:
            node-version: 'latest'
        - run: npm i @openapitools/openapi-generator-cli -g
        - run: openapi-generator-cli generate -g rust -i https://www.thebluealliance.com/swagger/api_v3.json -o .
        - run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "Generated Rust client library"
            git push origin HEAD:tba
